### ISSUE TITLE
Publish a Standalone Extension

### ISSUE THREAD

**Issue by 6a68** [mozilla-lockwise/lockwise-addon#141]
## Checklist
* [x] Deploy signed builds to GitHub Releases (#108)
* [x] Link to GHR from https://lockbox.firefox.com (mozilla-lockbox/mozilla-lockbox.github.io#113)
* [x] Add support for auto-update (#45)

## Open Questions
* Extension localization?

## Related
- Depends on #45 (implement auto-update support)
- Depends on #105  (investigate hosting)
- Depends on #108 (deploy signed builds to GHR)
- Depends on mozilla-lockbox/mozilla-lockbox.github.io#113 (publish on website)
- Related to #188 (sunsetting)

**Comment by 6a68** [comment]
We'll also need an update URL to catch future changes, which is both a manifest key (`update_url`) within the addon, as well as a JSON file hosted on whatever website we use to host the addon
