### ISSUE TITLE
Lockwise Rebranding

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockwise/lockwise-addon#206]
## Must Haves
* [ ] Update favicon/toolbar icon (branded)
* [x] Update logo (branded w/ name) #213
* [x] Update product name text #213
* [x] Update text for "entry"/"entries" --> "login"/"logins" #213
* [x] Window Title to full product name #213

## Nice to Haves
* [ ] (Management) Reflow Header Bar (#210)
* [ ] (Management) Reflow list Sidebar (#211)
* [ ] (Management) Reflow Details Panel (#212)

## References
* [Desktop Changes](https://docs.google.com/document/d/1fxgK7PDwnZodUW6XJO0zv7Ozm85DJgzDrmQtqe53XUs/edit#heading=h.woqebvspymga)
* Full Logo ([svg](https://drive.google.com/file/d/1QXyFFw6wXIjqBJnbxpViSvp-vt8F_ZmV/view))
* Icon (svg) (_TBD_)

**Comment by 6a68** [comment]
we're picking the highlighted items in here: https://docs.google.com/document/d/1fxgK7PDwnZodUW6XJO0zv7Ozm85DJgzDrmQtqe53XUs/edit#
